### ISSUE TITLE
سبد خرید

### ISSUE THREAD

**Issue by F-Shourabadi** [likecodeingloveproblems/app#24]
اضافه کردن فیلد ورودی کدملی
اجباری کردن ورود اطلاعات خریدار

**Comment by likecodeingloveproblems** [comment]
سلام
فک کنم این مساله حل شده، البته مطمئن نیستم.

**Comment by likecodeingloveproblems** [comment]
لطفا این مساله رو بررسی کنید #1 @F-Shourabadi

**Comment by likecodeingloveproblems** [comment]
الان کد ملی هنگام خرید گرفته میشه و اکانتش هم با توجه به این مساله اصلاح می شود.
اما ی سوال دیگه شکل میگیره که به نظرم چون توی این مساله نمی گنجید مساله #2  رو ایجاد کردم.
